name: super_cripto_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.2
  currency_text_input_formatter: ^2.2.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_loading_overlay: ^1.0.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^14.6.3
  intl: any
  money_formatter: ^0.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  root_tester: ^0.0.5

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - .env
