name: super_cripto_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  go_router: ^14.6.3
  intl: any
  money_formatter: ^0.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - .env
